name: on-push
on:
  # run on push
  push:
    branches:
      - '**'

jobs:
  gen-affected:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    outputs:
      AFFECTED: ${{ steps.gen-affected.outputs.AFFECTED }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
          fetch-depth: 0
      - uses: ./.github/actions/init-job
      - id: gen-affected
        run: |
          AFFECTED=$(npm run get:affected --silent)
          echo $AFFECTED
          echo "::set-output name=AFFECTED::$AFFECTED"

  internal-client:
    timeout-minutes: 5
    if: ${{ needs.gen-affected.outputs.AFFECTED != '' }}
    runs-on: ubuntu-latest
    needs:
      - gen-affected
    env:
      # configuration:
      # https://blog.sentry.io/2019/12/17/using-github-actions-to-create-sentry-releases
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_DEPLOYMENT_ENVIRONMENT: 'production'
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
      GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
      GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-job
      - run: npx nx run internal-client:lint
      - run: npx nx run internal-client:validate-blog-posts --path=apps/internal-client/static/blog/
      - run: npx nx run internal-client:validate-static-projects --path=apps/internal-client/static/projects/
      - run: npx nx run internal-client:export
      - run: npx nx run internal-client:lighthouse
      # - run: npx nx run internal-client-e2e:ci
      #   env:
      #     E2E_BASE_URL: local
      # TODO: can this be removed?
      - run: npx rimraf dist/apps/internal-client/exported/bradtaniguchi-dev
      - uses: actions/upload-artifact@v2
        with:
          name: internal-client
          path: dist/apps/internal-client/exported
          retention-days: 3

  # Job that generates the storybook configuration for all projects that have it,
  # where the `storybook`` library will be built and manage ALL the projects.
  # together via composition. Or at least thats the plan.
  # All of these together will be deployed within the gh-page job.
  internal-storybooks:
    timeout-minutes: 5
    if: ${{ needs.gen-affected.outputs.AFFECTED != '' }}
    runs-on: ubuntu-latest
    needs:
      - gen-affected
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-job
      - run: npx nx run-many --target=build-storybook --all
      - run: mv dist/storybook/storybook/** dist/storybook/
      - uses: actions/upload-artifact@v2
        with:
          name: internal-storybooks
          path: dist/storybook
          retention-days: 3

  # Job that generates things based on internal tooling.
  # Deployed with the storybook project to gh-pages.
  internal-tools:
    timeout-minutes: 5
    if: ${{ needs.gen-affected.outputs.AFFECTED != '' }}
    runs-on: ubuntu-latest
    needs:
      - gen-affected
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-job
      - run: npx nx graph --file=dist/nx-graph/index.html
      - run: npx nx graph --file=dist/nx-graph/graph.json
      - uses: actions/upload-artifact@v2
        with:
          name: internal-nx-graph
          path: dist/nx-graph
          retention-days: 3
      - run: npx nx run-many --target=typedoc --all
      - uses: actions/upload-artifact@v2
        with:
          name: internal-docs
          path: dist/docs
          retention-days: 3
      - run: npm run build:config
      - uses: actions/upload-artifact@v2
        with:
          name: config
          path: dist/config.json
          retention-days: 3

  # Job that deploys all the "internal" information that is generated within:
  # internal-client
  # internal-storybooks
  # internal-tools
  #
  # If we are on the main branch, then this job will execute to gather and deploy all
  # of the static contents to the local github page.
  gh-pages:
    timeout-minutes: 5
    if: ${{ needs.gen-affected.outputs.AFFECTED != '' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - gen-affected
      - internal-client
      - internal-storybooks
      - internal-tools
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-job
      - run: mkdir dist
      - uses: actions/download-artifact@v2
        with:
          name: internal-client
          # This gets moved to the top-level dist, as it will
          # manage all the other contents.
          path: dist
      - uses: actions/download-artifact@v2
        with:
          name: internal-storybooks
          # This gets changed to be plural for a cleaner URL
          path: dist/storybooks
      - uses: actions/download-artifact@v2
        with:
          name: internal-nx-graph
          path: dist/nx-graph
      - uses: actions/download-artifact@v2
        with:
          name: internal-docs
          path: dist/docs
      - uses: actions/download-artifact@v2
        with:
          name: config
          # should make config.json available
          path: dist
      # DEBUG build
      - uses: actions/upload-artifact@v2
        with:
          name: gh-pages-dist
          path: dist
          retention-days: 1
      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: dist
      - uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          # SENTRY_URL: https://sentry.io/
        with:
          environment: production

  prod-test:
    timeout-minutes: 5
    if: ${{ needs.gen-affected.outputs.AFFECTED != '' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - gh-pages
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-job
      - run: npx playwright install
      - run: npx nx run internal-client-e2e:ci-prod
        env:
          E2E_BASE_URL: https://bradtaniguchi.dev/

  common:
    if: ${{ contains(fromJSON(needs.gen-affected.outputs.AFFECTED || '[]'), 'common') }}
    runs-on: ubuntu-latest
    needs:
      - gen-affected
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-job
      - run: npx nx run common:lint
      - run: npx nx run common:test

  common-react:
    if: ${{ contains(fromJSON(needs.gen-affected.outputs.AFFECTED || '[]'), 'common-react') }}
    runs-on: ubuntu-latest
    needs:
      - gen-affected
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-job
      - run: npx nx run common-react:lint
      - run: npx nx run common-react:test
      - run: npx nx run common-react:build # TODO: verify
