name: test-prod
on: workflow_dispatch

jobs:
  prod-test:
    timeout-minutes: 5
    if: ${{ needs.gen-affected.outputs.AFFECTED != '' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - gh-pages
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/init-job
      - run: npx playwright install
      - run: npx nx run internal-client-e2e:ci-prod
        env:
          E2E_BASE_URL: https://bradtaniguchi.dev/
